apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customereligible-ingress
  namespace: contact-details
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s 
    nginx.ingress.kubernetes.io/auth-remove-header: false    
    ingress.kubernetes.io/rewrite-target: /customer/api/v1/eligible
spec:
   tls:
   - secretName: tls-secret
   rules:
   - http:
       paths:
       - path: /customer/api/v1/eligible
         backend:
           serviceName: customereligible-service
           servicePort: 8081