apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-service
  namespace: ${k8s-namespace}
spec:
  selector:
    app: ${artifactId}-app
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${artifactId}-deployment
  namespace: ${k8s-namespace}
  labels:
    app: ${artifactId}-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${artifactId}-app
  template:
    metadata:
      labels:
        app: ${artifactId}-app
    spec:
      containers:
      - name: ${artifactId}-app
        image: fra.ocir.io/entercard/msp/proenv/${artifactId}_img:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_KUBE_SRV
          valueFrom:
            configMapKeyRef:
              name: ${artifactId}-configmap
              key: database-kube-srv
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ${artifactId}-secret
              key: database-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${artifactId}-secret
              key: database-password
      imagePullSecrets:
      - name: ocirsecret
